---
- name: Validate host
  ansible.builtin.import_tasks: validate.yml

- name: Install mesh services
  ansible.builtin.import_tasks: mesh.yml
  when: aap_mesh_instance_type | length > 0

- name: Install node services
  ansible.builtin.include_tasks: install_node.yml
  loop: "{{ aap_node_types }}"
  loop_control:
    loop_var: aap_node_type
