---
- name: Validate host
  ansible.builtin.import_tasks: validate.yml

- name: Stop mesh instance services
  ansible.builtin.include_tasks: mesh_manage.yml
  vars:
    aap_mesh_desired_state: stopped
  when:
    - aap_mesh_instance_type | length > 0
    - aap_state == 'stopped'

- name: Manage node service state
  ansible.builtin.systemd:
    name: "aap-{{ aap_node_type }}.service"
    state: "{{ aap_state }}"
    enabled: "{{ aap_state == 'started' }}"
    daemon_reload: true
  loop: >-
    {{
      (aap_manage_order | intersect(aap_node_types) | reverse)
      if aap_state == 'started'
      else (aap_manage_order | intersect(aap_node_types))
    }}
  loop_control:
    loop_var: aap_node_type
  when: >-
    not (aap_state == 'stopped'
    and aap_node_type in aap_mesh_node_types)

- name: Start mesh instance services
  ansible.builtin.include_tasks: mesh_manage.yml
  vars:
    aap_mesh_desired_state: started
  when:
    - aap_mesh_instance_type | length > 0
    - aap_state == 'started'
