---
- name: Validate node type is supported
  ansible.builtin.import_tasks: 
    file: validate.yml

- name: Stop instance mesh service
  ansible.builtin.systemd:
    name: "aap-instance-{{ aap_node_type }}.service"
    state: "{{ aap_state }}"
    enabled: "{{ aap_state == 'started' }}"
    daemon_reload: true
  when:
    - aap_node_type in aap_mesh_node_types
    - aap_state == 'stopped'

- name: Manage component service state
  ansible.builtin.systemd:
    name: "aap-{{ aap_node_type }}.service"
    state: "{{ aap_state }}"
    enabled: "{{ aap_state == 'started' }}"
    daemon_reload: true
  when: >-
    not (aap_state == 'stopped'
    and aap_node_type in aap_mesh_node_types)

- name: Start instance mesh service
  ansible.builtin.systemd:
    name: "aap-instance-{{ aap_node_type }}.service"
    state: "{{ aap_state }}"
    enabled: "{{ aap_state == 'started' }}"
    daemon_reload: true
  when:
    - aap_node_type in aap_mesh_node_types
    - aap_state == 'started'
