---
- name: Validate host
  ansible.builtin.import_tasks: validate.yml

- name: Remove node systemd unit
  ansible.builtin.file:
    path: "/etc/systemd/system/aap-{{ aap_node_type }}.service"
    state: absent
  loop: "{{ aap_node_types }}"
  loop_control:
    loop_var: aap_node_type

- name: Remove node script
  ansible.builtin.file:
    path: "/usr/local/bin/aap-{{ aap_node_type }}"
    state: absent
  loop: "{{ aap_node_types }}"
  loop_control:
    loop_var: aap_node_type

- name: Remove instance systemd unit
  ansible.builtin.file:
    path: "/etc/systemd/system/aap-instance-{{ aap_mesh_instance_type }}.service"
    state: absent
  when: aap_mesh_instance_type | length > 0

- name: Remove instance script
  ansible.builtin.file:
    path: "/usr/local/bin/aap-instance-{{ aap_mesh_instance_type }}"
    state: absent
  when: aap_mesh_instance_type | length > 0

- name: Remove encrypted API token
  ansible.builtin.file:
    path: /etc/credstore.encrypted/aap_token
    state: absent
  when: aap_mesh_instance_type | length > 0

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
