---
- name: Validate node type is supported
  ansible.builtin.assert:
    that:
      - aap_node_type is defined
      - aap_node_type in aap_inventory_group_map.values() | list
    fail_msg: >-
      Could not determine aap_node_type from installer inventory groups
      (automationcontroller, automationgateway, automationhub, execution_nodes,
      automationeda, redis).
      Set aap_node_type on the host or exclude database hosts.
